# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Project
version=1.1.0
group=com.mrbysco.fac

# Common
minecraft_version=1.21.1

# NeoForge
neo_version=21.1.121
neogradle.subsystems.parchment.minecraftVersion=1.21.1
neogradle.subsystems.parchment.mappingsVersion=2024.11.17
neogradle.subsystems.conventions.runs.create-default-run-per-type=false

# Fabric
fabric_version=0.115.0+1.21.1
fabric_loader_version=0.16.10

# Mod options
mod_name=ForeverAChild
mod_author=Mrbysco
mod_id=foreverachild

#Publishing
curseforge_id=418064
modrinth_id=iU6zcrZd