modLoader="javafml"
loaderVersion="[2,)"
issueTrackerURL="https://github.com/Mrbysco/ForeverAChild/issues"
license="MIT"

[[mods]]
modId="foreverachild"
version="${file.jarVersion}"
displayName="Forever A Child"
displayURL="https://www.curseforge.com/minecraft/mc-mods/forever-a-child"
authors="Mrbysco"
description='''
Allows you to stop baby animals from ageing further
'''
[[dependencies.foreverachild]]
modId="minecraft"
type="REQUIRED"
versionRange="[1.20.4,1.21)"
ordering="NONE"
side="BOTH"
[[mixins]]
config = "foreverachild.mixins.json"